# Generated by Django 4.0.1 on 2022-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_savedroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='end',
            field=models.CharField(default='School Entrance', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='start',
            field=models.CharField(default='Laidlaw South', max_length=100),
            preserve_default=False,
        ),
    ]
